### ISSUE TITLE
Beard import fails with DuplicateCommand when beard folder name is different to beard name

### ISSUE THREAD

**Issue by nasfarley88** [LanceMaverick/skybeard-2#123]
For an example, do

```
$ utils/getbeard.py BabyFeederBeard
```

And then try and use the beard. This create the error:

```
Traceback (most recent call last):
  File "./main.py", line 263, in <module>
    main(config)
  File "./main.py", line 155, in main
    "one beard.".format(cmd.cmd))
__main__.DuplicateCommand: The command /startbabyfeed occurs in more than one beard.
```

**Comment by LanceMaverick** [comment]
Merged pull request to fix this. Thanks.
