### ISSUE TITLE
No module name 'config'

### ISSUE THREAD

**Issue by artemis-beta** [LanceMaverick/skybeard-2#140]
Result of running [tests](https://circleci.com/gh/artemis-beta/skybeard-2/7) on latest release within CircleCI.

```
ImportError: Failed to import test module: test_config
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-3.6.0/lib/python3.6/site-packages/nose2/plugins/loader/discovery.py", line 200, in _find_tests_in_file
    module = util.module_from_name(module_name)
  File "/home/ubuntu/virtualenvs/venv-3.6.0/lib/python3.6/site-packages/nose2/util.py", line 90, in module_from_name
    __import__(name)
  File "/home/ubuntu/skybeard-2/test_config.py", line 7, in <module>
    import config
ModuleNotFoundError: No module named 'config'
```

**Comment by LanceMaverick** [comment]
Issue with switching from config.py to config.yml. Now tests config using config.yml.example and works fine. See https://github.com/LanceMaverick/skybeard-2/commit/a15256aa86e2e050ec0f0a30b248fe2d52bd401d and https://github.com/LanceMaverick/skybeard-2/commit/0bd01b2a8010b5806e6bc77758af9930df637fab
